// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbrxfO062tPIZgQJ6KgbgiEjlHtcZC9g',
    appId: '1:964586820164:web:3ec140d2cac9958dd1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    authDomain: 'cahatapp-3ec8a.firebaseapp.com',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsh3T54tRcPJmpnQiOx4owv_4GHTXxLg',
    appId: '1:964586820164:android:548a4962f58b9a38d1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlqMwUSQxb2lCOcNgOKbndnBelwm_CbQ',
    appId: '1:964586820164:ios:1fe488614ed782e4d1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
    iosClientId: '964586820164-bgh6c2ravm6bp5a117qe2n3s5rghpgkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYlqMwUSQxb2lCOcNgOKbndnBelwm_CbQ',
    appId: '1:964586820164:ios:1fe488614ed782e4d1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
    iosClientId: '964586820164-bgh6c2ravm6bp5a117qe2n3s5rghpgkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFbrxfO062tPIZgQJ6KgbgiEjlHtcZC9g',
    appId: '1:964586820164:web:7995d978a0292091d1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    authDomain: 'cahatapp-3ec8a.firebaseapp.com',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
  );
}
